---
title: "DataDive"
author: "Tina (Tiantian) Yin"
date: "November 17, 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## 
```{r, message=FALSE}
library(gdata)
library(ggplot2)
library(tidyverse)
library(readxl)
library(stringr)
library(plotly)
```

     
```{r}
data <- read.csv('Data/QMSSDataDive_Q2_OilReserve.csv')
# add label of resource level 
data$Oil.Reserve[is.na(data$Oil.Reserve)] <- 0
data$resource[data$Oil.Reserve == 0] <- 0
data$resource[data$Oil.Reserve <= 100 & data$Oil.Reserve != 0] <- 1
data$resource[data$Oil.Reserve >100 & data$Oil.Reserve <= 2000] <- 2
data$resource[data$Oil.Reserve > 2000 & data$Oil.Reserve <= 8000] <- 3
data$resource[data$Oil.Reserve > 8000] <- 4

data_sub <- data[, c("country", "EITI", "resource")]


yrgdp <- names(data)
gdp <- data[str_detect(yrgdp, "yrpctgdp_*")]
subdata <- data[, c(1, 2)]
subdatagdp <- cbind(subdata, gdp)
subdatagdp <- t(subdatagdp)
```

```{r}
colnames(subdatagdp) <- subdatagdp[1,]
subdatagdp <- subdatagdp[c(-1, -2), ]

Year <- str_extract(rownames(subdatagdp), "[0-9]{4}")
subdatagdp <- cbind(Year, subdatagdp)

subdatagdp <- as.data.frame(subdatagdp)
EIFI <- data[data$EITI == 1, ]
subdatagdp <- gather(subdatagdp, "Country", "GDP", 2:33)
subdatagdp$Year <- as.Date(subdatagdp$Year, '%Y')
subdatagdp$GDP <- as.numeric(as.character(subdatagdp$GDP))
df2.1 <- merge(subdatagdp, data_sub, by.x = "Country", by.y = "country")
```

```{r}
summary(lm(GDP~as.factor(resource) + as.factor(EITI) + Year, data = df2.1))
```



```{r}
ggplotly(ggplot(subdatagdp) + geom_line(aes(x = Year, y = GDP, color = Country, group = 1)))
```

```{r}
Q1 <- read.csv('Data/Q1_CompanyIndicators_FINAL-OilGas.csv')
PE <- names(Q1)
PE <- Q1[str_detect(PE, 'P.E.Q*')]
subQ1 <- Q1[, 1]
PEdata <- cbind(Q1[, 1], PE)
PEdata <- t(PEdata)
colnames(PEdata) <- PEdata[1,]
PEdata <- PEdata[-1, ]
PEYear <- str_extract(rownames(PEdata), "[0-9]{4}")
PEdata <- cbind(PEYear, PEdata)
#PEdata$time <- rownames(PEdata)
PESeasons <- str_extract(rownames(PEdata), "[Q][0-9]")
PEdata <- cbind(PESeasons, PEdata)
PEdata <- as.data.frame(PEdata)
PEdatagather <- gather(PEdata, "Company", "PE", 3:102)
#PEdatagather$PEYear <- as.Date(PEdatagather$PEYear, '%Y')
PEdatagather$PE <- as.numeric(as.character(PEdatagather$PE))
PEdatagather$PETime <- paste(PEdatagather$PEYear,"-",PEdata$PESeasons)

####### data for regression
Trans <- Q1[, c(1, 3, 6, 7, 9, 10)]
df1.1 <- merge(PEdatagather, Trans, by = 'Company')
EU <- str_extract(df1.1$EU.Transparency.Directive, "Yes*")
df1.1 <- cbind(df1.1, EU)
df1.1$EU <- as.character(df1.1$EU)
df1.1$EU[is.na(df1.1$EU)] <- "No"
df1.1$Norway..Bors.Axess.[df1.1$Norway..Bors.Axess. == "yes"] <- "Yes"
df1.1noutl <- df1.1[df1.1$Company != 'Suncor Energy Inc', ]
```

```{r}
summary(lm(PE~as.factor(Transparent) + as.factor(EU) + as.factor(Norway..Bors.Axess.) + as.factor(Toronto..TSX.Venture.), data = df1.1noutl))
```

```{r}
df1.1sub <- df1.1noutl[df1.1noutl$Transparent == "Yes", ]
summary(lm(PE ~ as.factor(EU) + as.factor(Norway..Bors.Axess.) + as.factor(Toronto..TSX.Venture.), data = df1.1sub))
```



```{r}
ggplotly(ggplot(PEdatagather) + geom_line(aes(x = PETime, y = PE, color = Company, group = 1))) # + ylim(c(0,200)
```

```{r}
df <- data %>%group_by(resource) %>% summarise(Count = n())
ggplot(df) + geom_bar(aes(x = resource, y = as.integer(Count), fill = as.factor(resource)), stat = "identity") + theme_bw() + ggtitle("Oil Reserve Level of Country") + labs(x = "Level of Oil Reserve", y = "Number of Countries" ) + theme(plot.title = element_text(size = 18, hjust = 0.5)) + guides(fill=guide_legend(title="Level of Oil Reserve"))
```














